services:
  # server:
  #   image: "nginx:stable-alpine"
  #   ports:
  #     - "8000:80"
  #   volumes:
  #     - ./src:/var/www/html
  #     - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
  #   depends_on:
  #     - php
  #     - mysql

  server:
    build:
      context: .
      dockerfile: ./dockerfiles/nginx.dockerfile
    ports:
      - "8000:80"
    depends_on:
      - php
      - mysql

  php:
    build:
      context: .
      dockerfile: ./dockerfiles/php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated
    ports:
      - "3000:9000"

  mysql:
    image: "mysql:8.4"
    env_file:
      - ./env/mysql.env
    volumes:
      - mysql_data:/var/lib/mysql

  composer:
    build:
      context: .
      dockerfile: ./dockerfiles/composer.dockerfile
    volumes:
      - ./src:/var/www/html:delegated

  artisan:
    build:
      context: .
      dockerfile: ./dockerfiles/php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated
    entrypoint: ["php", "/var/www/html/artisan"]
  npm:
    image: "node:22-alpine"
    working_dir: /var/www/html
    entrypoint: ["npm"]
    volumes:
      - ./src:/var/www/html

# networks:
#   laravel:
#     driver: bridge

volumes:
  mysql_data:
